# .github/workflows/generate-ascii.yml
name: Generate ASCII Artwork
on:
  push:
    branches:
      - master
  

jobs:
  deploy:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: step3 timeout
        run: echo "step3 timeout"
      - name: step4 timeout
        run: sleep 300s  
           
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "The value for stepvar1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step2
        run: |
          echo "The value for step2"
          sleep 600s