# .github/workflows/generate-ascii.yml
name: Generate ASCII Artwork
on:
  push:
    branches:
      - master

concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "The value for stepvar1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step2
        run: |
          echo "The value for step2"
          sleep 600s